(define (domain hospitalcity)
  (:requirements :strips :typing :negative-preconditions)
  (:types injured location ambulance hospital)
  (:predicates (built ?h - hospital ?la - location)
	            (arrived ?a - ambulance ?la - location)
               (at ?i - injured ?la - location)
               (in ?i - injured ?a - ambulance)
	            (attend ?i - injured ?h - hospital)
               (full ?a - ambulance)
	            (link ?la - location ?lb - location))
  (:action pick
     :parameters (?i - injured ?a - ambulance ?la - location)
     :precondition (and (arrived ?a ?la) (at ?i ?la) (not (full ?a)) )
     :effect (and (in ?i ?a) (not (at ?i ?la)) (full ?a))
  )
  (:action drop
     :parameters (?i - injured ?a - ambulance ?h - hospital ?la - location)
     :precondition (and (built ?h ?la) (arrived ?a ?la) (full ?a) )
     :effect (and (attend ?i ?h) (not (full ?a)) )
  )
  (:action move
     :parameters (?a - ambulance ?la - location ?lb - location)
     :precondition (and (link ?la ?lb) (arrived ?a ?la))
     :effect (and (arrived ?a ?lb) (not (arrived ?a ?la)) )
  )
)

